package cn.lcy.mobilesearch.trans.mysql.model;
// Generated 2017-1-16 5:25:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebpageComSankuaiMeituan generated by hbm2java
 */
@Entity
@Table(name = "webpage_com_sankuai_meituan", catalog = "ias")
public class WebpageComSankuaiMeituan implements java.io.Serializable {

	private Integer id;
	private String packageName;
	private String activityName;
	private String webUrl;
	private String webUrlMd5;
	private String title;
	private String content;
	private String type;
	private String params;
	private BigDecimal crawlTimestamp;

	public WebpageComSankuaiMeituan() {
	}

	public WebpageComSankuaiMeituan(String packageName, String activityName, String webUrl, String webUrlMd5,
			String title, String content, String type, String params, BigDecimal crawlTimestamp) {
		this.packageName = packageName;
		this.activityName = activityName;
		this.webUrl = webUrl;
		this.webUrlMd5 = webUrlMd5;
		this.title = title;
		this.content = content;
		this.type = type;
		this.params = params;
		this.crawlTimestamp = crawlTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "package_name")
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "activity_name")
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Column(name = "web_url")
	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	@Column(name = "web_url_md5", length = 40)
	public String getWebUrlMd5() {
		return this.webUrlMd5;
	}

	public void setWebUrlMd5(String webUrlMd5) {
		this.webUrlMd5 = webUrlMd5;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "params")
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "crawl_timestamp", precision = 60, scale = 0)
	public BigDecimal getCrawlTimestamp() {
		return this.crawlTimestamp;
	}

	public void setCrawlTimestamp(BigDecimal crawlTimestamp) {
		this.crawlTimestamp = crawlTimestamp;
	}

}
