package cn.lcy.mobilesearch.trans.mysql.model;
// Generated 2017-1-16 5:25:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebpageTvDanmakuBili generated by hbm2java
 */
@Entity
@Table(name = "webpage_tv_danmaku_bili", catalog = "ias")
public class WebpageTvDanmakuBili implements java.io.Serializable {

	private Integer id;
	private String packageName;
	private String activityName;
	private String webUrl;
	private String webUrlMd5;
	private String title;
	private String content;
	private BigDecimal crawlTimestamp;

	public WebpageTvDanmakuBili() {
	}

	public WebpageTvDanmakuBili(String packageName, String activityName, String webUrl, String webUrlMd5, String title,
			String content, BigDecimal crawlTimestamp) {
		this.packageName = packageName;
		this.activityName = activityName;
		this.webUrl = webUrl;
		this.webUrlMd5 = webUrlMd5;
		this.title = title;
		this.content = content;
		this.crawlTimestamp = crawlTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "package_name")
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "activity_name")
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Column(name = "web_url")
	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	@Column(name = "web_url_md5", length = 40)
	public String getWebUrlMd5() {
		return this.webUrlMd5;
	}

	public void setWebUrlMd5(String webUrlMd5) {
		this.webUrlMd5 = webUrlMd5;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "crawl_timestamp", precision = 60, scale = 0)
	public BigDecimal getCrawlTimestamp() {
		return this.crawlTimestamp;
	}

	public void setCrawlTimestamp(BigDecimal crawlTimestamp) {
		this.crawlTimestamp = crawlTimestamp;
	}

}
